### PR TITLE
Added es6-promise to gulpfile after installing with npm

### PR DESCRIPTION
**Pull request by dlwebdev**
Was getting an error about es6-promise. Installed and added to gulpfile.

### CODE REVIEW

**Comment by dlwebdev** [comment]
May just be my VM. Going to destroy it and try again as I don't think I updated that system first.

**Comment by vjwilson** [comment]
@ECUdweber , 

Let me know how that goes. Angular has it's own version of the Q promise library built in, so that you don't need any ES6 support.

The computer I was developing the sample app on actually died in the middle of it, so I had to pull the repo onto another computer and `npm install` afresh. It ran fine on that second machine, but it is also used for dev, so I may have gotten a hidden dependency for free both times.

**Comment by ECUdweber** [comment]
Rebuilt the vm and updated/upgraded and still got that error. I don't think it would hurt to include it anyways.

**Comment by dlwebdev** [comment]
Node was way out of date on that vm. Updating took care of it.

**Pull request closed without merging**
